### ISSUE TITLE
The Plot.ly library is actually open source, MIT-licensed

### ISSUE THREAD

**Issue by dandv** [alanmitchell/bmon#75]
Found https://github.com/alanmitchell/bmon/wiki/Alternatives-to-Highcharts via a web search for HighCharts alternatives.

https://github.com/plotly/plotly.js/ is MIT-licensed now.

**Comment by alanmitchell** [comment]
Yes, we just finished converting our code to Plotly.  Thanks very much for open sourcing your software!
